# Nixpacks configuration for Railway deployment
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd packages/db && pnpm exec prisma generate",
  "cd ../../apps/api && pnpm build"
]

[start]
cmd = "pnpm run migrate:deploy && cd apps/api && pnpm start"

[variables]
NODE_ENV = "production"
PORT = "3001"
